services:
  frontend:
    build:
      target: development
    volumes:
      - ../app/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  backend:
    build:
      target: development
    volumes:
      - ../app/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 